run:
  skip-dirs:
    - analyzer/testdata

linters:
  enable:
    - errcheck
    - gosimple
    - revive
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
